name: Github Actions for Benerator
on: [push]
jobs:
  Compile-Benerator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'
          distribution: 'adopt'
      - name: Build with maven
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
